export const judge = {
  id: "ashutosh_kumar",
  name: "Hon'ble Mr. Justice Ashutosh Kumar",
  title: "Chief Justice",
  avatar: "https://ghconline.gov.in/wp-content/uploads/2018/06/HCJ-Ashutosh-Kumar.jpg",
  biography:
    "Hon'ble Mr. Justice Ashutosh Kumar was enrolled as an advocate in 1990 and practiced extensively in constitutional, civil and criminal matters before various High Courts and the Supreme Court of India. He was elevated as a Judge of the Gauhati High Court on 07.01.2015 and has since served on several important administrative and judicial committees of the Court.",
  details: [
    { label: "Parent High Court", value: "Gauhati" },
    { label: "Stream", value: "Bar" },
    { label: "Date of Birth", value: "23.10.1965" },
    { label: "Date of Elevation", value: "07.01.2015" },
    { label: "Date of Transfer", value: "-" },
    { label: "Date of Retirement", value: "22.10.2027" },
    {
      label: "Postal Address",
      value:
        "A-1C/57, Chaltlang-Salem Veng, Aizawl.\nCamp: Gauhati High Court Judges Guest House, Kharghuli.",
    },
    { label: "Place of Stationing", value: "Principal Seat" },
  ],
};

const placeholderAvatar = "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=400&h=500&fit=crop";
export const placeholderBio = "Biography placeholder.";

export const judges = [
  {
    id: "ashutosh_kumar",
    name: "Hon'ble Mr. Justice Ashutosh Kumar",
    title: "Chief Justice",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2018/06/HCJ-Ashutosh-Kumar.jpg",
    biography:
      "Hon’ble Mr. Justice Ashutosh Kumar was born on 1st October 1966. After his schooling from St Michaels’ High School, Patna, he graduated from St. Stephens’ College, Delhi University. Justice Kumar did his LLB. from Campus Law Centre, Delhi University. Enrolled as an advocate on 9th July 1991, at Patna High Court. As an advocate Justice Kumar has appeared in important criminal matters including matter related to convicts on Death Row. He was a Government Pleader for the State of Bihar for a short period. He has been elevated as a judge of Patna High Court on 15th of May 2014. He was transferred to Delhi High Court on 07th January 2015 and was repatriated again to Patna High Court on 24th November 2017. Took oath as Chief Justice of the Gauhati High Court on 21st July, 2025.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "01.10.1966" },
      { label: "Date of Elevation", value: "" },
      { label: "Date of Transfer", value: "" },
      { label: "Date of Retirement", value: "30.09.2028" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "" },
    ],
  },
  {
    id: "michael_zothankhuma",
    name: "Hon’ble Mr. Justice Michael Zothankhuma",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2018/06/HMJ-M-Zothankhuma.jpg",
    biography:
      "Born on 23.10.1965. Did schooling from St. Edmund's School, Shillong. Obtained B.A. (Hons.) in English from Hindu College under Delhi University. Completed LL.B from Campus Law Centre under Delhi University. Designated as Senior Advocate on 06.09.2010. Elevated as Additional Judge, Gauhati High Court on 07.01.2015. Appointed as Judge of the Gauhati High Court on 3rd January, 2017.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "23.10.1965" },
      { label: "Date of Elevation", value: "07.01.2015" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "22.10.2027" },
      {
        label: "Postal Address",
        value:
          "A-1C/57, Chaltlang-Salem Veng, Aizawl.\nCamp: Gauhati High Court Judges Guest House, Kharghuli.",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "094361-41332 (M)" },
    ],
  },
  {
    id: "kalyan_rai_surana",
    name: "Hon’ble Mr. Justice Kalyan Rai Surana",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2021/09/KRSurana111.jpg",
    biography:
      "Born on December 13, 1965. Graduated in Commerce (Major in Management Accountancy & Taxation) in 1988. Obtained LL.B degree in 1991. Enrolled as an Advocate on August 14, 1992. Practiced in various fields of law in the Gauhati High Court and subordinate Courts and also appeared before various Courts and Tribunals in Kolkata and New Delhi. Appointed as Additional Judge of the Gauhati High Court on November 15, 2016. Became permanent Judge w.e.f. 12.11.2018.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "13.12.1965" },
      { label: "Date of Elevation", value: "15.11.2016" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "12.12.2027" },
      {
        label: "Postal Address",
        value:
          "Bunglow No. 8, Near High Court Guest House, Kharghuli Main Road, Guwahati, Kamrup (M), Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "nelson_sailo",
    name: "Hon’ble Mr. Justice Nelson Sailo",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2018/06/Nelson-Sailo-4.jpg",
    biography:
      "Justice Nelson Sailo obtained Bachelor’s Degree in Arts and in Law from the North Eastern Hill University, Shillong. He enrolled himself in the Bar Council of Assam, Nagaland, Meghalaya, Manipur, Tripura, Mizoram and Arunachal Pradesh on 21.03.1996 and began his practice in Guwahati. He later shifted his practice to Aizawl and was appointed as Government Advocate, Public Prosecutor and then as Additional Advocate General, Mizoram. He was designated as a Senior Advocate by the High Court on 06.09.2010 and elevated as an Additional Judge of the High Court on 15.11.2016. He became a permanent Judge on 12.11.2018.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "09.10.1968" },
      { label: "Date of Elevation", value: "15.11.2016" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "08.10.2030" },
      {
        label: "Postal Address",
        value:
          "Bunglow No. 6, Near High Court Guest House, Kharghuli Main Road, Guwahati, Kamrup (M), Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "ajit_borthakur",
    name: "Hon’ble Mr. Justice Ajit Borthakur",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2018/06/Ajit-Borthakur.jpg",
    biography:
      "Born on 01-12-1961. Obtained B.A. (Hons) degree from Cotton College, Guwahati in 1982. Obtained LL.B. degree from Guwahati University Law College, Guwahati in 1986. Enrolled as an Advocate in the Bar Council of Assam, Nagaland, Meghalaya, Manipur, Tripura, Mizoram and Arunachal Pradesh on 23-09-1987. Joined in the Assam Judicial Service in the year 1989. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 15.11.2016. Became permanent Judge w.e.f. 12.11.2018.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "01.12.1961" },
      { label: "Date of Elevation", value: "15.11.2016" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "30.11.2023" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "sanjay_kumar_medhi",
    name: "Hon’ble Mr. Justice Sanjay Kumar Medhi",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2018/06/SKM.jpeg",
    biography:
      "Born on 07.03.1971. Obtained Bachelor’s Degree in Arts from Cotton College, Guwahati in 1991. Obtained LL.B. Degree from Government Law College, Guwahati in 1994 and LL.M. Degree from the same college in 1997. Enrolled as an Advocate on 24.08.1994. Designated as Senior Advocate on 06.04.2017. Elevated as Additional Judge of the Gauhati High Court on 19.11.2018. Became permanent Judge w.e.f. 10.11.2020.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "07.03.1971" },
      { label: "Date of Elevation", value: "19.11.2018" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "06.03.2033" },
      {
        label: "Postal Address",
        value:
          "Official Residence of Judge, Gauhati High Court, M.G. Road, Uzanbazar, Guwahati-781001, Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "nani_tagia",
    name: "Hon’ble Mr. Justice Nani Tagia",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2018/11/Nani-Tagia.jpg",
    biography:
      "Born on 16.05.1969. Obtained Bachelor’s Degree in Arts from J.N. College, Pasighat in 1989. Obtained LL.B. Degree from Campus Law Centre, University of Delhi in 1993. Enrolled as an Advocate on 18.02.1994. Designated as Senior Advocate on 12.08.2014. Elevated as Additional Judge of the Gauhati High Court on 19.11.2018. Became permanent Judge w.e.f. 10.11.2020.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "16.05.1969" },
      { label: "Date of Elevation", value: "19.11.2018" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "15.05.2031" },
      {
        label: "Postal Address",
        value:
          "Bunglow No. 5, Near High Court Guest House, Kharghuli Main Road, Guwahati, Kamrup (M), Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "manish_choudhury",
    name: "Hon’ble Mr. Justice Manish Choudhury",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2019/01/Manish-Choudhury.jpg",
    biography:
      "Born on 01.03.1972. Obtained Bachelor’s Degree in Science (Physics) from Cotton College, Guwahati in 1992. Obtained LL.B. Degree from Government Law College, Guwahati in 1995. Enrolled as an Advocate on 12.09.1995. Designated as Senior Advocate on 06.04.2017. Elevated as Additional Judge of the Gauhati High Court on 18.01.2019. Became permanent Judge w.e.f. 10.11.2020.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "01.03.1972" },
      { label: "Date of Elevation", value: "18.01.2019" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "28.02.2034" },
      {
        label: "Postal Address",
        value:
          "Bunglow No. 3, Near High Court Guest House, Kharghuli Main Road, Guwahati, Kamrup (M), Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "soumitra_saikia",
    name: "Hon’ble Mr. Justice Soumitra Saikia",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2019/11/Soumitra-Saikia.jpg",
    biography:
      "Born on 25.07.1970. Obtained Bachelor’s Degree in Arts from Cotton College, Guwahati in 1991. Obtained LL.B. Degree from Government Law College, Guwahati in 1994. Enrolled as an Advocate on 24.08.1994. Designated as Senior Advocate on 06.04.2017. Elevated as Additional Judge of the Gauhati High Court on 26.11.2019. Became permanent Judge w.e.f. 13.10.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "25.07.1970" },
      { label: "Date of Elevation", value: "26.11.2019" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "24.07.2032" },
      {
        label: "Postal Address",
        value:
          "Bunglow No. 2, Near High Court Guest House, Kharghuli Main Road, Guwahati, Kamrup (M), Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "parthivjyoti_saikia",
    name: "Hon’ble Mr. Justice Parthivjyoti Saikia",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2019/11/Parthivjyoti-Saikia.jpg",
    biography:
      "Born on 18.04.1965. Obtained Bachelor’s Degree in Arts from Nowgong College in 1986. Obtained LL.B. Degree from Government Law College, Guwahati in 1991. Enrolled as an Advocate on 20.09.1991. Joined in the Assam Judicial Service in the year 1992. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 26.11.2019. Became permanent Judge w.e.f. 13.10.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "18.04.1965" },
      { label: "Date of Elevation", value: "26.11.2019" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "17.04.2027" },
      {
        label: "Postal Address",
        value:
          "Bunglow No. 4, Near High Court Guest House, Kharghuli Main Road, Guwahati, Kamrup (M), Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "s_hukato_swu",
    name: "Hon’ble Mr. Justice S. Hukato Swu",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2019/11/S-Hukato-Swu.jpg",
    biography:
      "Born on 01.01.1960. Obtained Bachelor’s Degree in Arts from St. Anthony's College, Shillong in 1981. Obtained LL.B. Degree from Delhi University in 1986. Enrolled as an Advocate on 23.08.1986. Joined in the Nagaland Judicial Service in the year 1987. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 26.11.2019. Became permanent Judge w.e.f. 13.10.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "01.01.1960" },
      { label: "Date of Elevation", value: "26.11.2019" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "31.12.2021" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "Kohima Bench" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "malasri_nandi",
    name: "Hon’ble Mrs. Justice Malasri Nandi",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2021/10/Mrs.-Malasri-Nandi.jpg",
    biography:
      "Born on 24.06.1963. Obtained Bachelor’s Degree in Arts from Lady Keane College, Shillong. Obtained LL.B. Degree from Shillong Law College. Enrolled as an Advocate on 20.02.1990. Joined in the Assam Judicial Service in the year 1992. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 13.10.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "24.06.1963" },
      { label: "Date of Elevation", value: "13.10.2021" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "23.06.2025" },
      {
        label: "Postal Address",
        value: "Old CJ Bungalow, Uzanbazar, Guwahati, Kamrup (M), Assam",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "marli_vankung",
    name: "Hon’ble Mrs. Justice Marli Vankung",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2021/10/Mrs.-Marli-Vankung.jpg",
    biography:
      "Born on 04.03.1964. Obtained Bachelor’s Degree in Arts from St. Mary's College, Shillong. Obtained LL.B. Degree from Shillong Law College. Enrolled as an Advocate on 25.02.1988. Joined in the Mizoram Judicial Service in the year 1990. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 13.10.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "04.03.1964" },
      { label: "Date of Elevation", value: "13.10.2021" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "03.03.2026" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "Aizawl Bench" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "arun_dev_choudhury",
    name: "Hon’ble Mr. Justice Arun Dev Choudhury",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2021/11/Arun-Dev-Choudhury.jpg",
    biography:
      "Born on 29.10.1971. Obtained Bachelor’s Degree in Science from B. Borooah College, Guwahati in 1993. Obtained LL.B. Degree from Government Law College, Guwahati in 1996. Enrolled as an Advocate on 08.11.1996. Designated as Senior Advocate on 06.04.2017. Elevated as Additional Judge of the Gauhati High Court on 05.11.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "29.10.1971" },
      { label: "Date of Elevation", value: "05.11.2021" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "28.10.2033" },
      {
        label: "Postal Address",
        value: "Judge's Bungalow No. I, Panjabari, Guwahati-37",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "kakheto_sema",
    name: "Hon’ble Mr. Justice Kakheto Sema",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2021/10/Kakheto-Sema.jpg",
    biography:
      "Born on 06.07.1963. Obtained Bachelor’s Degree in Arts from St. Edmund's College, Shillong in 1983. Obtained LL.B. Degree from Delhi University in 1988. Enrolled as an Advocate on 20.09.1988. Designated as Senior Advocate on 03.08.2011. Elevated as Additional Judge of the Gauhati High Court on 13.10.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "06.07.1963" },
      { label: "Date of Elevation", value: "13.10.2021" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "05.07.2025" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "Kohima Bench" },
      { label: "Telephone", value: "" },
    ],
  },
  {
    id: "devashis_baruah",
    name: "Hon’ble Mr. Justice Devashis Baruah",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2021/10/Devashis-Baruah.jpg",
    biography:
      "Born on 22.02.1973. Obtained Bachelor’s Degree in Arts from Cotton College, Guwahati in 1993. Obtained LL.B. Degree from Government Law College, Guwahati in 1996. Enrolled as an Advocate on 12.09.1996. Designated as Senior Advocate on 06.04.2017. Elevated as Additional Judge of the Gauhati High Court on 13.10.2021.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "22.02.1973" },
      { label: "Date of Elevation", value: "13.10.2021" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "21.02.2035" },
      {
        label: "Postal Address",
        value: "Judge's Bungalow No. IV, Panjabari, Guwahati-37",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "susmita_phukan_khaund",
    name: "Hon’ble Mrs. Justice Susmita Phukan Khaund",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2022/08/Honble-Mrs.-Justice-Susmita-Phukan-Khaund.jpg",
    biography:
      "Born on 22.11.1964. Obtained Bachelor’s Degree in Arts from Cotton College, Guwahati. Obtained LL.B. Degree from Government Law College, Guwahati. Enrolled as an Advocate on 22.02.1991. Joined in the Assam Judicial Service in the year 1995. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 16.08.2022.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "22.11.1964" },
      { label: "Date of Elevation", value: "16.08.2022" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "21.11.2026" },
      {
        label: "Postal Address",
        value: "Judge's Bungalow No. II, Panjabari, Guwahati-37",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "mitali_thakuria",
    name: "Hon’ble Mrs. Justice Mitali Thakuria",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2022/08/Honble-Mrs.-Justice-Mitali-Thakuria.jpg",
    biography:
      "Born on 01.01.1965. Obtained Bachelor’s Degree in Arts from Handique Girls' College, Guwahati. Obtained LL.B. Degree from Government Law College, Guwahati. Enrolled as an Advocate on 16.09.1991. Joined in the Assam Judicial Service in the year 1995. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 16.08.2022.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "01.01.1965" },
      { label: "Date of Elevation", value: "16.08.2022" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "31.12.2026" },
      {
        label: "Postal Address",
        value: "Judge's Bungalow No. III, Panjabari, Guwahati-37",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "kardak_ete",
    name: "Hon’ble Mr. Justice Kardak Ete",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2023/03/Kardak-Ete.jpg",
    biography:
      "Born on 16.04.1974. Obtained Bachelor’s Degree in Arts from Dera Natung Government College, Itanagar in 1995. Obtained LL.B. Degree from Gauhati University Law College in 1999. Enrolled as an Advocate on 24.01.2000. Designated as Senior Advocate on 18.01.2019. Elevated as Additional Judge of the Gauhati High Court on 13.03.2023.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "16.04.1974" },
      { label: "Date of Elevation", value: "13.03.2023" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "15.04.2036" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "Itanagar Bench" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "mridul_kumar_kalita",
    name: "Hon’ble Mr. Justice Mridul Kumar Kalita",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2023/04/Mridul-Kumar-Kalita.jpg",
    biography:
      "Born on 22.04.1968. Obtained Bachelor’s Degree in Science from Cotton College, Guwahati in 1988. Obtained LL.B. Degree from Government Law College, Guwahati in 1991. Enrolled as an Advocate on 20.09.1991. Joined in the Assam Judicial Service in the year 1999. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 20.04.2023.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "22.04.1968" },
      { label: "Date of Elevation", value: "20.04.2023" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "21.04.2030" },
      {
        label: "Postal Address",
        value: "Judge's Bungalow No. V, Panjabari, Guwahati-37",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "budi_habung",
    name: "Hon’ble Mr. Justice Budi Habung",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2023/09/Budi-Habung.jpg",
    biography:
      "Born on 01.03.1971. Obtained Bachelor’s Degree in Arts from Jawaharlal Nehru College, Pasighat. Obtained LL.B. Degree from Campus Law Centre, University of Delhi. Enrolled as an Advocate on 28.02.1997. Joined in the Arunachal Pradesh Judicial Service in the year 2010. Worked in various capacities in the District Judiciary. Elevated as Additional Judge of the Gauhati High Court on 12.09.2023.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Service" },
      { label: "Date of Birth", value: "01.03.1971" },
      { label: "Date of Elevation", value: "12.09.2023" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "28.02.2033" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "Itanagar Bench" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "kaushik_goswami",
    name: "Hon’ble Mr. Justice Kaushik Goswami",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2023/11/Kaushik-Goswami.jpg",
    biography:
      "Born on 26.11.1972. Obtained Bachelor’s Degree in Arts from Cotton College, Guwahati. Obtained LL.B. Degree from Government Law College, Guwahati. Enrolled as an Advocate on 18.08.1997. Designated as Senior Advocate on 08.02.2022. Elevated as Additional Judge of the Gauhati High Court on 02.11.2023.",
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "Bar" },
      { label: "Date of Birth", value: "26.11.1972" },
      { label: "Date of Elevation", value: "02.11.2023" },
      { label: "Date of Transfer", value: "-" },
      { label: "Date of Retirement", value: "25.11.2034" },
      {
        label: "Postal Address",
        value: "Judge's Bungalow No. VI, Panjabari, Guwahati-37",
      },
      { label: "Place of Stationing", value: "Principal Seat" },
      { label: "Telephone", value: "-" },
    ],
  },
  {
    id: "pranjal_das",
    name: "Hon’ble Mr. Justice Pranjal Das",
    title: "",
    avatar: "https://ghconline.gov.in/wp-content/uploads/2018/06/HMJ-Pranjal-Das1.jpg",
    biography: placeholderBio,
    details: [
      { label: "Parent High Court", value: "Gauhati" },
      { label: "Stream", value: "" },
      { label: "Date of Birth", value: "" },
      { label: "Date of Elevation", value: "30/07/2025" },
      { label: "Date of Transfer", value: "" },
      { label: "Date of Retirement", value: "" },
      { label: "Postal Address", value: "" },
      { label: "Place of Stationing", value: "" },
      { label: "Telephone", value: "" },
    ],
  },
];

export const serviceCards = [
  { id: "live_streaming", icon: "video", color: "#1E63D6" },
  { id: "cause_list", icon: "calendar", color: "#10B981" },
  { id: "display_board", icon: "clipboard-list", color: "#F59E0B" },
  // { id: "judgment_search", icon: "search1", color: "#6C40FF" },
  { id: "justice_clock", icon: "clock", color: "#F97316" },
];

export const holidayTags = [
  { label: "All", color: "#0D4199" },
  { label: "Public", color: "#10B981" },
  { label: "Restricted", color: "#F97316" },
  { label: "Working Saturday", color: "#6C40FF" },
];

export const holidays = [
  // Jan
  { label: "1st – 2nd New Year Holiday", badge: "Public", badgeColor: "#cf2b0eff", month: 0, year: 2026 },
  { label: "3rd Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 0, year: 2026 },
  { label: "12th – 16th Magh Bihu & Tusu Puja", badge: "Public", badgeColor: "#cf2b0eff", month: 0, year: 2026 },
  { label: "17th Silpi Divas", badge: "Restricted", badgeColor: "#2563EB", month: 0, year: 2026 },
  { label: "17th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 0, year: 2026 },
  { label: "23rd Sri Panchami", badge: "Public", badgeColor: "#cf2b0eff", month: 0, year: 2026 },
  { label: "23rd Netaji's Birth Day", badge: "Restricted", badgeColor: "#2563EB", month: 0, year: 2026 },
  { label: "26th Republic Day", badge: "Public", badgeColor: "#cf2b0eff", month: 0, year: 2026 },
  { label: "27th Busu Dima Festival", badge: "Restricted", badgeColor: "#2563EB", month: 0, year: 2026 },
  { label: "27th Gwther Bathaw Saan (Baithow Puja)", badge: "Restricted", badgeColor: "#2563EB", month: 0, year: 2026 },
  { label: "31st Medam-Me-Phi", badge: "Public", badgeColor: "#cf2b0eff", month: 0, year: 2026 },
  { label: "31st Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 0, year: 2026 },

  // Feb
  { label: "1st Bir Chilarai Divas", badge: "Restricted", badgeColor: "#2563EB", month: 1, year: 2026 },
  { label: "4th Shab e-Barat", badge: "Restricted", badgeColor: "#2563EB", month: 1, year: 2026 },
  { label: "7th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 1, year: 2026 },
  { label: "15th Siva Ratri", badge: "Public", badgeColor: "#cf2b0eff", month: 1, year: 2026 },
  { label: "17th Karbi Dehal Kachir Dom", badge: "Restricted", badgeColor: "#2563EB", month: 1, year: 2026 },
  { label: "18th Ali-Aye-Linqang", badge: "Restricted", badgeColor: "#2563EB", month: 1, year: 2026 },
  { label: "21st Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 1, year: 2026 },
  { label: "23rd Bathow Puja/Khiring Khiring Baithow Puja", badge: "Restricted", badgeColor: "#2563EB", month: 1, year: 2026 },

  // Mar
  { label: "3rd – 4th Dol Jatra/ Holi", badge: "Public", badgeColor: "#cf2b0eff", month: 2, year: 2026 },
  { label: "7th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 2, year: 2026 },
  { label: "17th Shab-e-Qadr (Laylat ul-Qadr)", badge: "Restricted", badgeColor: "#2563EB", month: 2, year: 2026 },
  { label: "21st Id-ul-Fitre", badge: "Public", badgeColor: "#cf2b0eff", month: 2, year: 2026 },
  { label: "21st Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 2, year: 2026 },
  { label: "31st Mahavir Jayanti", badge: "Restricted", badgeColor: "#2563EB", month: 2, year: 2026 },

  // Apr
  { label: "3rd Good Friday", badge: "Public", badgeColor: "#cf2b0eff", month: 3, year: 2026 },
  { label: "4th Easter Saturday", badge: "Restricted", badgeColor: "#2563EB", month: 3, year: 2026 },
  { label: "4th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 3, year: 2026 },
  { label: "13th – 18th BIHU VACATION", badge: "Public", badgeColor: "#cf2b0eff", month: 3, year: 2026 },
  { label: "15th Deuri Bihu", badge: "Restricted", badgeColor: "#2563EB", month: 3, year: 2026 },
  { label: "18th Tithi of Sri Sri Damodar Dev", badge: "Restricted", badgeColor: "#2563EB", month: 3, year: 2026 },
  { label: "18th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 3, year: 2026 },
  { label: "21st Sati Sadhani Divas", badge: "Restricted", badgeColor: "#2563EB", month: 3, year: 2026 },
  { label: "22nd Tithi of Gopal Dev", badge: "Restricted", badgeColor: "#2563EB", month: 3, year: 2026 },

  // May
  { label: "1st Buddha Purnima & May Day", badge: "Public", badgeColor: "#cf2b0eff", month: 4, year: 2026 },
  { label: "2nd Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 4, year: 2026 },
  { label: "16th Tithi of Hari Dev", badge: "Restricted", badgeColor: "#2563EB", month: 4, year: 2026 },
  { label: "16th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 4, year: 2026 },
  { label: "27th Id-Uz-Zuha", badge: "Public", badgeColor: "#cf2b0eff", month: 4, year: 2026 },
  { label: "30th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 4, year: 2026 },
  { label: "31st Baikhow Festival", badge: "Restricted", badgeColor: "#2563EB", month: 4, year: 2026 },

  // Jun
  { label: "1st Janmotsav of Sri Sri Madhab Dev", badge: "Restricted", badgeColor: "#2563EB", month: 5, year: 2026 },
  { label: "6th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 5, year: 2026 },
  { label: "20th Death Anniversary of Bishnu Prasad Rabha", badge: "Restricted", badgeColor: "#2563EB", month: 5, year: 2026 },
  { label: "20th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 5, year: 2026 },
  { label: "26th Muharram", badge: "Restricted", badgeColor: "#2563EB", month: 5, year: 2026 },
  { label: "29th – 30th SUMMER VACATION", badge: "Public", badgeColor: "#cf2b0eff", month: 5, year: 2026 },

  // Jul
  { label: "1st – 10th SUMMER VACATION", badge: "Public", badgeColor: "#cf2b0eff", month: 6, year: 2026 },
  { label: "4th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 6, year: 2026 },
  { label: "13th Birth Day of Nepali Poet Bhanu Bhakta Acharya", badge: "Restricted", badgeColor: "#2563EB", month: 6, year: 2026 },
  { label: "18th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 6, year: 2026 },

  // Aug
  { label: "1st Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 7, year: 2026 },
  { label: "13th Death Anniversary of Bir Tikendrajit", badge: "Restricted", badgeColor: "#2563EB", month: 7, year: 2026 },
  { label: "15th Independence Day", badge: "Public", badgeColor: "#cf2b0eff", month: 7, year: 2026 },
  { label: "15th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 7, year: 2026 },
  { label: "26th Fateha-Dwaj-Daham", badge: "Restricted", badgeColor: "#2563EB", month: 7, year: 2026 },
  { label: "29th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 7, year: 2026 },

  // Sep
  { label: "1st Tithi of Sri Sri Madhab Dev", badge: "Public", badgeColor: "#cf2b0eff", month: 8, year: 2026 },
  { label: "4th Janmastami", badge: "Public", badgeColor: "#cf2b0eff", month: 8, year: 2026 },
  { label: "5th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 8, year: 2026 },
  { label: "12th Tithi of Srimanta Sankar Dev", badge: "Public", badgeColor: "#cf2b0eff", month: 8, year: 2026 },
  { label: "16th Abirbhab Tithi of Sri Sri Thakur Anukul Chandra", badge: "Restricted", badgeColor: "#2563EB", month: 8, year: 2026 },
  { label: "19th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 8, year: 2026 },
  { label: "21st Janmotsava of Srimanta Sankar Dev", badge: "Public", badgeColor: "#cf2b0eff", month: 8, year: 2026 },
  { label: "22nd Karam Puja", badge: "Restricted", badgeColor: "#2563EB", month: 8, year: 2026 },

  // Oct
  { label: "2nd Birth day of Mahatma Gandhi", badge: "Public", badgeColor: "#cf2b0eff", month: 9, year: 2026 },
  { label: "3rd Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 9, year: 2026 },
  { label: "17th – 31st LONG VACATION", badge: "Public", badgeColor: "#cf2b0eff", month: 9, year: 2026 },
  { label: "17th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 9, year: 2026 },
  { label: "31st Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 9, year: 2026 },

  // Nov
  { label: "1st Kuki Chavanq Kut", badge: "Restricted", badgeColor: "#2563EB", month: 10, year: 2026 },
  { label: "7th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 10, year: 2026 },
  { label: "8th – 9th Kali Puja/Diwali", badge: "Public", badgeColor: "#cf2b0eff", month: 10, year: 2026 },
  { label: "11th Bhatri Dwitia & Abirbhab Tithi of Sri Bhubaneswar Sadhu Thakur", badge: "Restricted", badgeColor: "#2563EB", month: 10, year: 2026 },
  { label: "15th Chhat Puja", badge: "Restricted", badgeColor: "#2563EB", month: 10, year: 2026 },
  { label: "21st Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 10, year: 2026 },
  { label: "24th Guru Nanak's Birthday", badge: "Public", badgeColor: "#cf2b0eff", month: 10, year: 2026 },
  { label: "24th Lachit Divas & Death Anniversary of Guru Teg Bahadurji", badge: "Restricted", badgeColor: "#2563EB", month: 10, year: 2026 },

  // Dec
  { label: "2nd Assam Divas", badge: "Restricted", badgeColor: "#2563EB", month: 11, year: 2026 },
  { label: "5th Sikpuoi Ruoi", badge: "Restricted", badgeColor: "#2563EB", month: 11, year: 2026 },
  { label: "5th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 11, year: 2026 },
  { label: "10th Martyr's Day", badge: "Restricted", badgeColor: "#2563EB", month: 11, year: 2026 },
  { label: "19th Working Saturday", badge: "Working Saturday", badgeColor: "#10B981", month: 11, year: 2026 },
  { label: "24th – 31st WINTER VACATION Christmas Holidays", badge: "Public", badgeColor: "#cf2b0eff", month: 11, year: 2026 },
];

export const menuUrls = {
  "judges_sc_sitting": "https://ghconline.gov.in/index.php/honourable-sitting-judges-of-the-supreme-court-of-india/",
  "judges_sc_former": "https://ghconline.gov.in/index.php/former-honble-judges-of-the-supreme-court-of-india-chief-justice-of-india-who-served-as-chief-justice-honble-judge-of-this-high-court/",
  "judges_ghc_former_cj": "https://ghconline.gov.in/index.php/former-honourable-chief-justices-of-gauhati-high-court/",
  "judges_ghc_former": "https://ghconline.gov.in/index.php/former-honourable-judges-of-the-gauhati-high-court/",
  "judges_transferred": "https://ghconline.gov.in/index.php/honourable-chief-justices-and-judges-of-the-gauhati-high-court-appointed-or-transferred-as-chief-justices-of-other-high-court/",
  "bench_kohima": "https://kohimahighcourt.gov.in",
  "bench_aizawl": "http://ghcazlbench.nic.in",
  "bench_itanagar": "http://ghcitanagar.gov.in",
  "reg_present": "https://ghconline.gov.in/index.php/registry/",
  "reg_former_gen": "https://ghconline.gov.in/index.php/former-registrar-general/",
  "reg_former_vig": "https://ghconline.gov.in/index.php/former-registrar-i-e-vigilance/",
  "reg_former_sec": "https://ghconline.gov.in/index.php/former-registrar-cum-principal-secretary-to-honble-the-chief-justice/",
  "reg_former_jud": "https://ghconline.gov.in/index.php/former-registrar-judicial/",
  "reg_former_admin": "https://ghconline.gov.in/index.php/former-registrar-administration/",
  "reg_former_est": "https://ghconline.gov.in/index.php/former-registrar-establishment/",
  "link_sci": "https://www.sci.gov.in/",
  "link_sclsc": "https://sclsc.gov.in/",
  "link_ghclsc": "https://ghconline.gov.in/ghclsc",
  "link_lri": "https://ghcservices.assam.gov.in/lri/",
  "link_jjc": "http://ghcjjmc.assam.gov.in",
  "link_bar": "https://ghconline.gov.in/index.php/bar-under-construction/",
  "link_med": "https://ghconline.gov.in/Mediation/index.html",
  "link_ja": "https://jaa.assam.gov.in/",
  "link_lawmin": "http://lawmin.gov.in/",
  "recruitment_judicial": "https://ghconline.gov.in/index.php/recruitment-judicial-officer/",
  "recruitment_principal": "https://ghconline.gov.in/index.php/recruitment-notices/",
  "recruitment_district": "https://ghconline.gov.in/index.php/recruitment-subordinate-courts/",
  "recruitment_other": "https://ghconline.gov.in/index.php/recruitment-other-organisations/",
  "recruitment_papers": "https://ghconline.gov.in/index.php/previous-year-question-papers/",
  "ebook_history": "https://ghconline.gov.in/index.php/gauhati-high-court-history-heritage-assamese-version/",
  "ebook_platinum": "https://ghconline.gov.in/index.php/platinum-jubilee-souvenir-of-the-gauhati-high-court-2023-2/",
  "district_courts": "https://ghconline.gov.in/index.php/district-courts/",
};

export const civilCaseTypes = [
  { label: "abc", value: "211" },
  { label: "Adml.S.", value: "164" },
  { label: "AIR(REF)", value: "201" },
  { label: "Arb.A.", value: "139" },
  { label: "Arb.Appln.", value: "219" },
  { label: "Arb.P.", value: "138" },
  { label: "Bkg.p.", value: "118" },
  { label: "CA", value: "187" },
  { label: "CAC", value: "183" },
  { label: "CAPL", value: "47" },
  { label: "C.APPLN", value: "181" },
  { label: "CAVT", value: "178" },
  { label: "CC(CIV)", value: "7" },
  { label: "CE.Ref.", value: "152" },
  { label: "CEREF", value: "83" },
  { label: "C.Ex.App.", value: "213" },
  { label: "CMAppl.", value: "109" },
  { label: "CO", value: "97" },
  { label: "Co.App.", value: "117" },
  { label: "Co.Appl.", value: "115" },
  { label: "COB(FA)", value: "6" },
  { label: "COB(MFA)", value: "5" },
  { label: "COB(T)", value: "81" },
  { label: "COJO", value: "34" },
  { label: "COMAPL", value: "4" },
  { label: "Comm.App.Div.", value: "232" },
  { label: "COMPET", value: "3" },
  { label: "CONTAPP", value: "94" },
  { label: "Cont.App.(C)", value: "143" },
  { label: "Cont.Cas(C)", value: "142" },
  { label: "Cont.Cas(C)(Suo Moto)", value: "229" },
  { label: "COP(C)", value: "2" },
  { label: "Co.Pet.", value: "114" },
  { label: "CP", value: "68" },
  { label: "C.PTN.", value: "180" },
  { label: "CR", value: "1" },
  { label: "CRAPPL", value: "80" },
  { label: "C.Ref.", value: "104" },
  { label: "CREF", value: "13" },
  { label: "CREV", value: "14" },
  { label: "CREV(H)", value: "15" },
  { label: "C.REVN", value: "188" },
  { label: "CR(HC)", value: "8" },
  { label: "CR(LAB)", value: "9" },
  { label: "CR(LAN)", value: "10" },
  { label: "CR(M)", value: "196" },
  { label: "CR(OTH)", value: "11" },
  { label: "CRP", value: "102" },
  { label: "CRP(IO)", value: "216" },
  { label: "CRP (Suo Moto)", value: "227" },
  { label: "CR(SER)", value: "12" },
  { label: "CS", value: "95" },
  { label: "CS(OS)", value: "159" },
  { label: "Cus.Ref.", value: "151" },
  { label: "DS", value: "72" },
  { label: "EC", value: "182" },
  { label: "EDREF", value: "16" },
  { label: "ED(REF)", value: "199" },
  { label: "El.App.", value: "135" },
  { label: "El.Pet.", value: "134" },
  { label: "EP", value: "17" },
  { label: "Ex.Appl.(OS)", value: "161" },
  { label: "Ex.FA.", value: "106" },
  { label: "Ex.P.", value: "105" },
  { label: "Ex.SA.", value: "107" },
  { label: "FA", value: "18" },
  { label: "FA(D)", value: "60" },
  { label: "FA/MA(F)", value: "186" },
  { label: "FAO", value: "98" },
  { label: "FA(OS)", value: "160" },
  { label: "FA/SA", value: "185" },
  { label: "FA(T)", value: "212" },
  { label: "GTA/WTA/EDA", value: "150" },
  { label: "GTREF", value: "21" },
  { label: "GT(REF)", value: "198" },
  { label: "GTR/WTR/EDR", value: "149" },
  { label: "Gua.P.", value: "125" },
  { label: "Hill.Appeal", value: "233" },
  { label: "I.A.", value: "218" },
  { label: "I.A.(Civil)", value: "220" },
  { label: "Insurance App.", value: "141" },
  { label: "Insurance Ref.", value: "140" },
  { label: "Intest.Cas.", value: "124" },
  { label: "IP(Appl.)", value: "137" },
  { label: "IP(M)", value: "136" },
  { label: "ITA", value: "148" },
  { label: "ITR", value: "147" },
  { label: "ITREF", value: "22" },
  { label: "IT(REF)", value: "195" },
  { label: "ITREF(A)", value: "88" },
  { label: "LA.App.", value: "127" },
  { label: "LA.Ref.", value: "126" },
  { label: "LPA", value: "23" },
  { label: "LPA/Sp.A", value: "101" },
  { label: "LPA(T)", value: "87" },
  { label: "MAC", value: "132" },
  { label: "MACApp.", value: "133" },
  { label: "MAF", value: "24" },
  { label: "MA(F)", value: "184" },
  { label: "MAF(T)", value: "25" },
  { label: "MA(S)", value: "65" },
  { label: "MAS(T)", value: "86" },
  { label: "Mat.App.", value: "121" },
  { label: "Mat.Cas.", value: "119" },
  { label: "Mat.Ref.", value: "120" },
  { label: "MC", value: "59" },
  { label: "MC(COP)", value: "82" },
  { label: "MC(CR)", value: "26" },
  { label: "MC(CREV)", value: "27" },
  { label: "MCCRL. REVN", value: "193" },
  { label: "MC(EP)", value: "29" },
  { label: "MC(F)", value: "71" },
  { label: "MC(FA)", value: "79" },
  { label: "MC(MAF)", value: "28" },
  { label: "MC(N)", value: "205" },
  { label: "MC(RA)", value: "85" },
  { label: "MC(SA)", value: "30" },
  { label: "MC(WA)", value: "74" },
  { label: "MFA", value: "144" },
  { label: "MSA", value: "145" },
  { label: "M.S.(S.J.,C.S. and so on)", value: "162" },
  { label: "N.M.", value: "163" },
  { label: "OC", value: "90" },
  { label: "OJ", value: "92" },
  { label: "OTA", value: "31" },
  { label: "OT.Appl", value: "158" },
  { label: "OTC", value: "157" },
  { label: "OTR", value: "156" },
  { label: "PIL", value: "93" },
  { label: "PIL(Suo Moto)", value: "222" },
  { label: "RA", value: "70" },
  { label: "RA(CR)", value: "32" },
  { label: "RA(FA)", value: "33" },
  { label: "RA(MFA)", value: "35" },
  { label: "RAT", value: "66" },
  { label: "RCC", value: "128" },
  { label: "RCFA", value: "129" },
  { label: "RCRev.", value: "131" },
  { label: "RCSA", value: "130" },
  { label: "REP", value: "36" },
  { label: "RERA APPEAL", value: "231" },
  { label: "Review.Pet.", value: "103" },
  { label: "Revn.Pet.", value: "217" },
  { label: "RFA", value: "96" },
  { label: "RLPA", value: "37" },
  { label: "RP(FAM.CT.)", value: "122" },
  { label: "RPT", value: "67" },
  { label: "RSA", value: "99" },
  { label: "SA", value: "39" },
  { label: "SAO", value: "100" },
  { label: "SA(T)", value: "40" },
  { label: "SCA", value: "84" },
  { label: "SCLP", value: "113" },
  { label: "SLP", value: "203" },
  { label: "SP.JC(Name of Act)", value: "146" },
  { label: "ST.Appl.", value: "154" },
  { label: "ST.Ref.", value: "153" },
  { label: "STREF", value: "41" },
  { label: "ST(REF)", value: "200" },
  { label: "ST.Rev.", value: "155" },
  { label: "Test.App.", value: "214" },
  { label: "Test.Cas.", value: "123" },
  { label: "Tr.P.(C).", value: "204" },
  { label: "TS", value: "77" },
  { label: "W", value: "176" },
  { label: "WA", value: "112" },
  { label: "WA(LAB)", value: "42" },
  { label: "WA(LAN)", value: "43" },
  { label: "WA(OTH)", value: "45" },
  { label: "WA(SER)", value: "44" },
  { label: "WA(T)", value: "64" },
  { label: "WP", value: "116" },
  { label: "WP(C)", value: "111" },
  { label: "WP(C)(Suo Moto)", value: "225" },
  { label: "WP(C)(Taken up)", value: "223" },
  { label: "WTREF", value: "46" },
  { label: "WT(REF)", value: "197" }
];

export const criminalCaseTypes = [
  { label: "AB", value: "49" },
  { label: "BA", value: "57" },
  { label: "Bail Appln.", value: "171" },
  { label: "Bail (Cancellation)", value: "235" },
  { label: "Cont.App.(Crl.)", value: "175" },
  { label: "Cont.Cas.(Crl.)", value: "174" },
  { label: "Cont.Case(Crl)(Suo Moto)", value: "228" },
  { label: "CRAPL", value: "52" },
  { label: "CR(CC)", value: "50" },
  { label: "CRDREF", value: "58" },
  { label: "Crl.A.", value: "166" },
  { label: "CRL.A(H)", value: "189" },
  { label: "CRL.A(J)", value: "190" },
  { label: "Crl.A(PMLA)", value: "234" },
  { label: "Crl.L.P.", value: "208" },
  { label: "Crl.M.Appl.", value: "172" },
  { label: "Crl.M.C.", value: "170" },
  { label: "CRL.O.APPN", value: "192" },
  { label: "CRL.OP(C)", value: "179" },
  { label: "CRL.O.REF", value: "202" },
  { label: "Crl.P.", value: "210" },
  { label: "Crl.Pet.", value: "209" },
  { label: "Crl.Pet.(Suo Moto)", value: "224" },
  { label: "Crl.Ref.", value: "169" },
  { label: "CRL.REF(H)", value: "206" },
  { label: "CRL.REV(H)", value: "194" },
  { label: "CRL.REVN", value: "191" },
  { label: "Crl.Rev.P.", value: "168" },
  { label: "Crl.Tr.", value: "165" },
  { label: "CR(MC)", value: "51" },
  { label: "CROA", value: "62" },
  { label: "CROA(C)", value: "69" },
  { label: "CROP", value: "63" },
  { label: "CROP(C)", value: "53" },
  { label: "CRREF", value: "54" },
  { label: "CRREF(H)", value: "55" },
  { label: "CRREV", value: "56" },
  { label: "CRREVAP", value: "75" },
  { label: "Death Sentence Ref.", value: "167" },
  { label: "GCA", value: "20" },
  { label: "I.A.(Crl.)", value: "221" },
  { label: "MC(CRAPL)", value: "76" },
  { label: "MC(CRREV)", value: "73" },
  { label: "Tr.P.(Crl.)", value: "177" },
  { label: "Tr.P(Crl)(Suo moto)", value: "230" },
  { label: "W.P.(Crl.)", value: "173" },
  { label: "WP(Crl)(Suo Moto)", value: "226" }
];
